<?php
// Variables
return [
  "creatorName" => "Portal Presensi",
  "creatorUrl" => "",
  "templateName" => "Portal Presensi",
  "templateSuffix" => "Digital",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Sistem Informasi dan Portal Presensi Digital",
  "templateKeyword" => "presensi, portal presensi, absensi digital",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "ogTitle" => "Portal Presensi Digital",
  "ogImage" => "",
  "ogType" => "website",
  "documentation" => "https://demos.pixinvent.com/vuexy-html-admin-template/documentation",
  "generator" => "",
  "changelog" => "https://demos.pixinvent.com/vuexy/changelog.html",
  "repository" => "https://github.com/pixinvent/vuexy-html-laravel-admin-template",
  "gitRepo" => "vuexy-html-laravel-admin-template",
  "gitRepoAccess" => "https://tools.pixinvent.com/github/github-access",
  "githubFreeUrl" => "https://github.com/pixinvent",
  "facebookUrl" => "https://www.facebook.com/pixinvents/",
  "twitterUrl" => "https://x.com/pixinvents",
  "githubUrl" => "https://github.com/pixinvent",
  "dribbbleUrl" => "https://dribbble.com/pixinvent",
  "instagramUrl" => "https://www.instagram.com/pixinvents/"
];
